import { SyntaxStyle } from "@opentui/core";

const mocha = {
  text: "#cdd6f4",
  subtext1: "#bac2de",
  subtext0: "#a6adc8",
  overlay2: "#9399b2",
  overlay1: "#7f849c",
  overlay0: "#6c7086",
  surface2: "#585b70",
  surface1: "#45475a",
  surface0: "#313244",
  base: "#1e1e2e",
  mantle: "#181825",
  crust: "#11111b",
  lavender: "#b4befe",
  blue: "#89b4fa",
  sapphire: "#74c7ec",
  sky: "#89dceb",
  teal: "#94e2d5",
  green: "#a6e3a1",
  yellow: "#f9e2af",
  peach: "#fab387",
  maroon: "#eba0ac",
  red: "#f38ba8",
  mauve: "#cba6f7",
  pink: "#f5c2e7",
  flamingo: "#f2cdcd",
  rosewater: "#f5e0dc",
};

export const catppuccinMochaSyntax = SyntaxStyle.fromTheme([
  { scope: ["default"], style: { foreground: mocha.text } },
  { scope: ["comment", "punctuation.comment"], style: { foreground: mocha.overlay0, italic: true } },
  { scope: ["string"], style: { foreground: mocha.green } },
  { scope: ["string.special", "character"], style: { foreground: mocha.teal } },
  { scope: ["number", "constant.numeric", "boolean"], style: { foreground: mocha.peach } },
  { scope: ["keyword", "operator"], style: { foreground: mocha.mauve, bold: true } },
  { scope: ["type", "type.builtin"], style: { foreground: mocha.yellow } },
  { scope: ["function", "function.call", "method"], style: { foreground: mocha.blue } },
  { scope: ["variable", "property", "field"], style: { foreground: mocha.text } },
  { scope: ["parameter"], style: { foreground: mocha.rosewater } },
  { scope: ["constant", "constant.builtin"], style: { foreground: mocha.peach } },
  { scope: ["attribute"], style: { foreground: mocha.red } },
  { scope: ["tag"], style: { foreground: mocha.maroon } },
  { scope: ["punctuation"], style: { foreground: mocha.subtext0 } },
]);
